//! Gemini API client implementation

use base64::Engine;
use reqwest::Client;
use serde::{Deserialize, Serialize};
use std::time::Duration;

use super::provider::{TranscriptionProvider, TranscriptionResult};
use crate::error::AppError;

const GEMINI_API_BASE: &str = "https://generativelanguage.googleapis.com/v1beta";
const DEFAULT_MODEL: &str = "gemini-2.5-flash-lite";
const MAX_RETRIES: u32 = 3;
const RETRY_DELAY_MS: u64 = 1000;

pub struct GeminiProvider {
    client: Client,
    api_key: String,
    model: String,
}

impl GeminiProvider {
    pub fn new(api_key: String, model: Option<String>) -> Self {
        Self {
            client: Client::new(),
            api_key,
            model: model.unwrap_or_else(|| DEFAULT_MODEL.to_string()),
        }
    }

    fn endpoint(&self) -> String {
        format!(
            "{}/models/{}:generateContent?key={}",
            GEMINI_API_BASE, self.model, self.api_key
        )
    }

    fn is_retryable_error(status: reqwest::StatusCode, body: &str) -> bool {
        let lower = body.to_lowercase();
        status.as_u16() == 429
            || status.as_u16() == 503
            || lower.contains("overloaded")
            || lower.contains("too many requests")
            || lower.contains("rate limit")
    }

    fn extract_text(response: GeminiResponse) -> Result<String, AppError> {
        if let Some(error) = response.error {
            return Err(AppError::Transcription(error.message));
        }

        let text = response
            .candidates
            .and_then(|c| c.into_iter().next())
            .and_then(|c| c.content.parts.into_iter().next())
            .and_then(|p| p.text)
            .ok_or_else(|| AppError::Transcription("No response generated by AI".to_string()))?;

        if text.trim().is_empty() {
            return Err(AppError::Transcription(
                "AI returned an empty response".to_string(),
            ));
        }

        Ok(text)
    }

    /// Execute a request with retry logic
    async fn execute_with_retry(&self, request: &GeminiRequest) -> Result<String, AppError> {
        let mut last_error = None;

        for attempt in 0..MAX_RETRIES {
            let response = match self.client.post(self.endpoint()).json(request).send().await {
                Ok(resp) => resp,
                Err(e) => {
                    last_error = Some(AppError::Transcription(format!("Request failed: {}", e)));
                    if attempt < MAX_RETRIES - 1 {
                        tokio::time::sleep(Duration::from_millis(
                            RETRY_DELAY_MS * (attempt as u64 + 1),
                        ))
                        .await;
                        continue;
                    }
                    break;
                }
            };

            let status = response.status();
            let body = response.text().await.unwrap_or_else(|_| "{}".to_string());

            if Self::is_retryable_error(status, &body) {
                last_error = Some(AppError::Transcription(format!(
                    "API error {}: {}",
                    status,
                    &body[..body.len().min(200)]
                )));

                if attempt < MAX_RETRIES - 1 {
                    tokio::time::sleep(Duration::from_millis(
                        RETRY_DELAY_MS * (attempt as u64 + 1),
                    ))
                    .await;
                    continue;
                }
                break;
            }

            if !status.is_success() {
                return Err(AppError::Transcription(format!(
                    "API error {}: {}",
                    status,
                    &body[..body.len().min(200)]
                )));
            }

            let gemini_response: GeminiResponse = serde_json::from_str(&body)
                .map_err(|e| AppError::Transcription(format!("Failed to parse response: {}", e)))?;

            return Self::extract_text(gemini_response);
        }

        Err(last_error
            .unwrap_or_else(|| AppError::Transcription("Request failed after retries".to_string())))
    }
}

// --- Request / Response types ---

#[derive(Serialize)]
struct GeminiRequest {
    #[serde(skip_serializing_if = "Option::is_none")]
    system_instruction: Option<SystemInstruction>,
    contents: Vec<Content>,
    #[serde(rename = "generationConfig", skip_serializing_if = "Option::is_none")]
    generation_config: Option<GenerationConfig>,
}

#[derive(Serialize)]
struct SystemInstruction {
    parts: Vec<TextPart>,
}

#[derive(Serialize)]
struct TextPart {
    text: String,
}

#[derive(Serialize)]
struct Content {
    parts: Vec<Part>,
}

#[derive(Serialize)]
#[serde(untagged)]
enum Part {
    Text { text: String },
    InlineData { inline_data: InlineData },
}

#[derive(Serialize)]
struct InlineData {
    mime_type: String,
    data: String,
}

#[derive(Serialize)]
struct GenerationConfig {
    temperature: f32,
    #[serde(rename = "maxOutputTokens")]
    max_output_tokens: u32,
}

#[derive(Deserialize)]
struct GeminiResponse {
    candidates: Option<Vec<Candidate>>,
    error: Option<GeminiError>,
}

#[derive(Deserialize)]
struct Candidate {
    content: CandidateContent,
}

#[derive(Deserialize)]
struct CandidateContent {
    parts: Vec<ResponsePart>,
}

#[derive(Deserialize)]
struct ResponsePart {
    text: Option<String>,
}

#[derive(Deserialize)]
struct GeminiError {
    message: String,
}

// --- Model listing ---

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ModelInfo {
    pub id: String,
    pub display_name: String,
}

#[derive(Deserialize)]
struct ModelsResponse {
    models: Option<Vec<ModelEntry>>,
}

#[derive(Deserialize)]
struct ModelEntry {
    name: String,
    #[serde(rename = "displayName")]
    display_name: Option<String>,
    #[serde(rename = "supportedGenerationMethods", default)]
    supported_generation_methods: Vec<String>,
}

impl GeminiProvider {
    /// List available Gemini models that support content generation
    pub async fn list_models(api_key: &str) -> Result<Vec<ModelInfo>, AppError> {
        let url = format!("{}/models?key={}", GEMINI_API_BASE, api_key);
        let client = Client::new();
        let response = client
            .get(&url)
            .send()
            .await
            .map_err(|e| AppError::Transcription(format!("Failed to list models: {}", e)))?;

        if !response.status().is_success() {
            let status = response.status();
            let body = response.text().await.unwrap_or_default();
            return Err(AppError::Transcription(format!(
                "Failed to list models ({}): {}",
                status,
                &body[..body.len().min(200)]
            )));
        }

        let body: ModelsResponse = response
            .json()
            .await
            .map_err(|e| AppError::Transcription(format!("Failed to parse models: {}", e)))?;

        let models = body
            .models
            .unwrap_or_default()
            .into_iter()
            .filter(|m| {
                m.supported_generation_methods
                    .contains(&"generateContent".to_string())
            })
            .map(|m| {
                let id = m
                    .name
                    .strip_prefix("models/")
                    .unwrap_or(&m.name)
                    .to_string();
                ModelInfo {
                    display_name: m.display_name.unwrap_or_else(|| id.clone()),
                    id,
                }
            })
            .collect();

        Ok(models)
    }
}

// --- Trait implementation ---

impl TranscriptionProvider for GeminiProvider {
    fn transcribe(
        &self,
        audio_data: &[u8],
        mime_type: &str,
        system_prompt: &str,
    ) -> std::pin::Pin<
        Box<dyn std::future::Future<Output = Result<TranscriptionResult, AppError>> + Send + '_>,
    > {
        let audio_base64 = base64::engine::general_purpose::STANDARD.encode(audio_data);
        let mime_type = mime_type.to_string();
        let system_prompt = system_prompt.to_string();

        Box::pin(async move {
            let request = GeminiRequest {
                system_instruction: Some(SystemInstruction {
                    parts: vec![TextPart {
                        text: system_prompt,
                    }],
                }),
                contents: vec![Content {
                    parts: vec![Part::InlineData {
                        inline_data: InlineData {
                            mime_type,
                            data: audio_base64,
                        },
                    }],
                }],
                generation_config: Some(GenerationConfig {
                    temperature: 0.1,
                    max_output_tokens: 8192,
                }),
            };

            let text = self.execute_with_retry(&request).await?;
            Ok(TranscriptionResult { text })
        })
    }

    fn test_connection(
        &self,
    ) -> std::pin::Pin<Box<dyn std::future::Future<Output = Result<bool, AppError>> + Send + '_>>
    {
        Box::pin(async move {
            let request = GeminiRequest {
                system_instruction: None,
                contents: vec![Content {
                    parts: vec![Part::Text {
                        text: "Respond with only: OK".to_string(),
                    }],
                }],
                generation_config: Some(GenerationConfig {
                    temperature: 0.1,
                    max_output_tokens: 10,
                }),
            };

            self.execute_with_retry(&request).await?;
            Ok(true)
        })
    }

    fn provider_name(&self) -> &str {
        "Gemini"
    }
}
