//! OpenAI Chat Completions API client implementation

use base64::Engine;
use reqwest::Client;
use serde::{Deserialize, Serialize};
use std::time::Duration;

use super::gemini::ModelInfo;
use super::provider::{TranscriptionProvider, TranscriptionResult};
use crate::error::AppError;

const OPENAI_API_BASE: &str = "https://api.openai.com/v1";
const DEFAULT_MODEL: &str = "gpt-4o-mini-audio-preview";
const MAX_RETRIES: u32 = 3;
const RETRY_DELAY_MS: u64 = 1000;

/// Known audio-capable model prefixes for Chat Completions with input_audio support
const AUDIO_MODEL_PREFIXES: &[&str] = &["gpt-4o-audio-preview", "gpt-4o-mini-audio-preview"];

/// Fallback models when API listing fails
const FALLBACK_MODELS: &[(&str, &str)] = &[
    ("gpt-4o-audio-preview", "GPT-4o Audio Preview"),
    ("gpt-4o-mini-audio-preview", "GPT-4o Mini Audio Preview"),
];

pub struct OpenAiProvider {
    client: Client,
    api_key: String,
    model: String,
}

impl OpenAiProvider {
    pub fn new(api_key: String, model: Option<String>) -> Self {
        Self {
            client: Client::new(),
            api_key,
            model: model.unwrap_or_else(|| DEFAULT_MODEL.to_string()),
        }
    }

    /// Map MIME type to OpenAI input_audio format
    fn audio_format(mime_type: &str) -> &'static str {
        match mime_type {
            "audio/wav" => "wav",
            // Opus/OGG not directly supported in input_audio; use mp3 per PRD
            _ => "mp3",
        }
    }

    fn is_retryable_error(status: reqwest::StatusCode, body: &str) -> bool {
        let lower = body.to_lowercase();
        status.as_u16() == 429
            || status.as_u16() == 503
            || lower.contains("rate limit")
            || lower.contains("overloaded")
    }

    fn extract_text(response: ChatCompletionResponse) -> Result<String, AppError> {
        let text = response
            .choices
            .into_iter()
            .next()
            .and_then(|c| c.message.content)
            .ok_or_else(|| AppError::Transcription("No response generated by AI".to_string()))?;

        if text.trim().is_empty() {
            return Err(AppError::Transcription(
                "AI returned an empty response".to_string(),
            ));
        }

        Ok(text)
    }

    fn extract_error(body: &str) -> String {
        if let Ok(err_resp) = serde_json::from_str::<OpenAiErrorResponse>(body) {
            err_resp.error.message
        } else {
            body[..body.len().min(200)].to_string()
        }
    }

    /// Execute a request with retry logic
    async fn execute_with_retry(
        &self,
        request: &ChatCompletionRequest,
    ) -> Result<String, AppError> {
        let mut last_error = None;
        let url = format!("{}/chat/completions", OPENAI_API_BASE);

        for attempt in 0..MAX_RETRIES {
            let response = match self
                .client
                .post(&url)
                .header("Authorization", format!("Bearer {}", self.api_key))
                .json(request)
                .send()
                .await
            {
                Ok(resp) => resp,
                Err(e) => {
                    last_error = Some(AppError::Transcription(format!("Request failed: {}", e)));
                    if attempt < MAX_RETRIES - 1 {
                        tokio::time::sleep(Duration::from_millis(
                            RETRY_DELAY_MS * (attempt as u64 + 1),
                        ))
                        .await;
                        continue;
                    }
                    break;
                }
            };

            let status = response.status();
            let body = response.text().await.unwrap_or_else(|_| "{}".to_string());

            if Self::is_retryable_error(status, &body) {
                last_error = Some(AppError::Transcription(format!(
                    "API error {}: {}",
                    status,
                    Self::extract_error(&body)
                )));

                if attempt < MAX_RETRIES - 1 {
                    tokio::time::sleep(Duration::from_millis(
                        RETRY_DELAY_MS * (attempt as u64 + 1),
                    ))
                    .await;
                    continue;
                }
                break;
            }

            if !status.is_success() {
                return Err(AppError::Transcription(format!(
                    "API error {}: {}",
                    status,
                    Self::extract_error(&body)
                )));
            }

            let chat_response: ChatCompletionResponse = serde_json::from_str(&body)
                .map_err(|e| AppError::Transcription(format!("Failed to parse response: {}", e)))?;

            return Self::extract_text(chat_response);
        }

        Err(last_error
            .unwrap_or_else(|| AppError::Transcription("Request failed after retries".to_string())))
    }

    /// List available audio-capable OpenAI models
    pub async fn list_models(api_key: &str) -> Result<Vec<ModelInfo>, AppError> {
        let url = format!("{}/models", OPENAI_API_BASE);
        let client = Client::new();
        let response = client
            .get(&url)
            .header("Authorization", format!("Bearer {}", api_key))
            .send()
            .await;

        let response = match response {
            Ok(resp) if resp.status().is_success() => resp,
            _ => {
                // Fallback to hardcoded list
                return Ok(FALLBACK_MODELS
                    .iter()
                    .map(|(id, name)| ModelInfo {
                        id: id.to_string(),
                        display_name: name.to_string(),
                    })
                    .collect());
            }
        };

        let body: ModelsListResponse = match response.json().await {
            Ok(b) => b,
            Err(_) => {
                return Ok(FALLBACK_MODELS
                    .iter()
                    .map(|(id, name)| ModelInfo {
                        id: id.to_string(),
                        display_name: name.to_string(),
                    })
                    .collect());
            }
        };

        let mut models: Vec<ModelInfo> = body
            .data
            .into_iter()
            .filter(|m| {
                AUDIO_MODEL_PREFIXES
                    .iter()
                    .any(|prefix| m.id.starts_with(prefix))
            })
            .map(|m| ModelInfo {
                display_name: humanize_model_id(&m.id),
                id: m.id,
            })
            .collect();

        if models.is_empty() {
            // Fallback if no audio models found
            models = FALLBACK_MODELS
                .iter()
                .map(|(id, name)| ModelInfo {
                    id: id.to_string(),
                    display_name: name.to_string(),
                })
                .collect();
        }

        models.sort_by(|a, b| a.id.cmp(&b.id));
        Ok(models)
    }
}

/// Humanize an OpenAI model ID into a display name
fn humanize_model_id(id: &str) -> String {
    id.split('-')
        .map(|part| {
            if part.chars().all(|c| c.is_ascii_digit()) {
                // Date parts stay as-is
                part.to_string()
            } else {
                let mut chars = part.chars();
                match chars.next() {
                    Some(c) => c.to_uppercase().to_string() + chars.as_str(),
                    None => String::new(),
                }
            }
        })
        .collect::<Vec<_>>()
        .join(" ")
}

// --- Request / Response types ---

#[derive(Serialize)]
struct ChatCompletionRequest {
    model: String,
    temperature: f32,
    max_tokens: u32,
    messages: Vec<Message>,
}

#[derive(Serialize)]
struct Message {
    role: String,
    content: MessageContent,
}

#[derive(Serialize)]
#[serde(untagged)]
enum MessageContent {
    Text(String),
    Parts(Vec<ContentPart>),
}

#[derive(Serialize)]
#[serde(tag = "type")]
enum ContentPart {
    #[serde(rename = "input_audio")]
    InputAudio { input_audio: InputAudio },
}

#[derive(Serialize)]
struct InputAudio {
    data: String,
    format: String,
}

#[derive(Deserialize)]
struct ChatCompletionResponse {
    choices: Vec<Choice>,
}

#[derive(Deserialize)]
struct Choice {
    message: ResponseMessage,
}

#[derive(Deserialize)]
struct ResponseMessage {
    content: Option<String>,
}

#[derive(Deserialize)]
struct OpenAiErrorResponse {
    error: OpenAiError,
}

#[derive(Deserialize)]
struct OpenAiError {
    message: String,
}

// --- Model listing types ---

#[derive(Deserialize)]
struct ModelsListResponse {
    data: Vec<ModelEntry>,
}

#[derive(Deserialize)]
struct ModelEntry {
    id: String,
}

// --- Trait implementation ---

impl TranscriptionProvider for OpenAiProvider {
    fn transcribe(
        &self,
        audio_data: &[u8],
        mime_type: &str,
        system_prompt: &str,
    ) -> std::pin::Pin<
        Box<dyn std::future::Future<Output = Result<TranscriptionResult, AppError>> + Send + '_>,
    > {
        let audio_base64 = base64::engine::general_purpose::STANDARD.encode(audio_data);
        let format = Self::audio_format(mime_type).to_string();
        let system_prompt = system_prompt.to_string();

        Box::pin(async move {
            let request = ChatCompletionRequest {
                model: self.model.clone(),
                temperature: 0.1,
                max_tokens: 8192,
                messages: vec![
                    Message {
                        role: "system".to_string(),
                        content: MessageContent::Text(system_prompt),
                    },
                    Message {
                        role: "user".to_string(),
                        content: MessageContent::Parts(vec![ContentPart::InputAudio {
                            input_audio: InputAudio {
                                data: audio_base64,
                                format,
                            },
                        }]),
                    },
                ],
            };

            let text = self.execute_with_retry(&request).await?;
            Ok(TranscriptionResult { text })
        })
    }

    fn test_connection(
        &self,
    ) -> std::pin::Pin<Box<dyn std::future::Future<Output = Result<bool, AppError>> + Send + '_>>
    {
        Box::pin(async move {
            let url = format!("{}/models", OPENAI_API_BASE);
            let response = self
                .client
                .get(&url)
                .header("Authorization", format!("Bearer {}", self.api_key))
                .send()
                .await
                .map_err(|e| AppError::Transcription(format!("Connection test failed: {}", e)))?;

            if response.status().is_success() {
                Ok(true)
            } else {
                let status = response.status();
                let body = response.text().await.unwrap_or_default();
                Err(AppError::Transcription(format!(
                    "Authentication failed ({}): {}",
                    status,
                    Self::extract_error(&body)
                )))
            }
        })
    }

    fn provider_name(&self) -> &str {
        "OpenAI"
    }
}
